version: '3.7'

networks:
  boilerplate:

volumes:
  mongodb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/mongodb/data/db
  mysql_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/mysql

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - boilerplate
    volumes:
      - mongodb_volume:/data/db
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - boilerplate
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: unless-stopped

  api:
    build: .
    hostname: api.boilerplate
    container_name: api
    command:
    - /bin/bash
    - -c
    - |
      ./hack/wait_for_it.sh --timeout=30 --host=mysql --port=3306 --strict -- \
      ./hack/wait_for_it.sh --timeout=30 --host=mongodb --port=27017 --strict -- \
      yarn start;
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGO_URI=mongodb
      - MYSQL_URL=mysql
    ports:
      - "3001:3001"
      - "8443:8443"
    networks:
      - boilerplate
    restart: unless-stopped
