version: '3.8'

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=dummy
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ${PWD}/hack/fixtures/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
